### ISSUE TITLE
the number of rows written does not match the actual scenario 

### ISSUE THREAD

**Issue by vitor-fagundes** [fragtastic/cis-benchmark-to-csv#13]
the csv file does not display all formatted data. following image: 

![image](https://user-images.githubusercontent.com/74776867/108541495-48c42200-72c1-11eb-9dc4-bd6e6d3c49a4.png)

can you help me?

**Comment by tomrwaller** [comment]
I'm also seeing this issue.

The benchmark I am using is the Microsoft Azure Foundations 1.3.1 benchmark. I use Adobe Reader to save the file as txt and when running I get about 44 of the 100+ items.

Using the RegEx 101 build and test site, I can see this is an issue with the RegEx. It grabs a couple of matches from the appendix, and some from the body. It definitely looks inconsistent.

**Comment by tomrwaller** [comment]
Here is an example of the Azure Foundations benchmark where the RegEx isn't matching correctly.

https://regex101.com/r/w8MdfV/1

**Comment by fragtastic** [comment]
@tomrwaller Your issue is that you exported the text on a Windows machine. Looking at your link I can see that several lines are split when they shouldn't be.
For whatever reason Adobe Acrobat DC on Windows will split lines incorrectly.

I have only so far had good exports from Adobe Acrobat DC on MacOS.
I haven't been able to sort out a workaround.

Testing against Azure Fundamentals 1.4.0 correctly exports 115 rows to Excel.
Additionally I have reverted back to using explicit scoring types in the regex, otherwise there are a couple erroneous matches.

If you're still experiencing any issue with it, feel free to open a separate issue for it.

**Comment by fragtastic** [comment]
@vitor-fagundes Microsoft Excel is notoriously bad for opening CSV files, in my experience.
I would recommend using the Excel output.

I'll close this issue since there have been many changes since that commit.
